In [2]:
import numpy as np

In [4]:
a = np.zeros(4)
print(a , a.shape   , a.dtype)

[0. 0. 0. 0.] (4,) float64


In [6]:
a = np.zeros((4,2))
print(a, a.shape , a.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] (4, 2) float64


In [8]:
a = np.random.random_sample(4)
print(a, a.shape, a.dtype)

[0.05263663 0.100699   0.73385881 0.98824419] (4,) float64


In [13]:
a = np.arange(4.)
print(a , a.shape , a.dtype)

[0. 1. 2. 3.] (4,) float64


In [23]:
a = np.random.rand(4)
print(a , a.shape , a.dtype)

[0.90416353 0.65100254 0.8862743  0.43014791] (4,) float64


In [24]:
a = np.array([1,2,3,4])
print(a , a.shape , a.dtype)

[1 2 3 4] (4,) int32


In [25]:
a = np.array([5.,4,3,7])
print(a , a.shape , a.dtype)

[5. 4. 3. 7.] (4,) float64


In [32]:
a = np.arange(10)
print(a[2],a[2].shape,", so we can infer the elemnts present in Vector(1-D array) are Scalar")
print(f"a[-1] : {a[-1]}")
try:
    c = a[10]
except Exception as e:
    print("The error message is:",e)

2 () , so we can infer the elemnts present in Vector(1-D array) are Scalar
a[-1] : 9
The error message is: index 10 is out of bounds for axis 0 with size 10


In [34]:
a = np.arange(10)
print("a         ",a)
c = a[2:7:1]
print(f"a[2:7:1] = {c}")
c = a[2:7:2]
print(f"a[2:7:2] = {c}")
c = a[3:]
print(f"a[3:] = {c}")
c = a[:3]
print(f"a[:3] = {c}")
c = a[:]
print(f"a[:] = {c}")

a          [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]
a[3:] = [3 4 5 6 7 8 9]
a[:3] = [0 1 2]
a[:] = [0 1 2 3 4 5 6 7 8 9]


In [35]:
a = np.array([1,2,3,4])
b = -a
print(b)
b = np.sum(a)
print(b)
b = np.mean(a)
print(b)
b = a**2
print(b)

[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


Vector  - Vector elementwise operations

In [36]:
a = np.array([-1,-2,3,4])
b = np.array([1,2,3,4])
print(f"a+b = {a+b}")

a+b = [0 0 6 8]


when dimension of vectors differ elementwise operations are not possible

In [39]:
c = np.array([1,2])
try:
    a+c
except Exception as e:
    print("The error messasge is :",e )

The error messasge is : operands could not be broadcast together with shapes (4,) (2,) 


Scalar Vector Operation:

In [41]:
a = np.array([1,2,3,4])
b = 5 * a
print(b)

[ 5 10 15 20]


Vector Vector Dot Product

The dot product multiplies the values in two vectors element-wise and then sums the result. Vector dot product requires the dimensions of the two vectors to be the same.

Lets try to implement using for loop

In [44]:
def my_dot(a,b):
    m = a.shape[0]
    sum =0
    for i in range(m):
        sum = sum + a[i] * b[i]
    return sum

In [45]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])
print("dot product :",my_dot(a,b))

dot product : 80


Lets try the same with numpy:

In [50]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])
c = np.dot(a,b)
print(c)
print(f"Shape = {c.shape}" ,"so the dot product is scalar")

80
Shape = () so the dot product is scalar


Lets See The Time Diffrence between Both These Approach

In [56]:
import time
np.random.seed(1)
a = np.random.rand(10000000)
b = np.random.rand(10000000)
# vectorization approach
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(f"{c:.4f} , time taken by vectorized approach,{1000 * (toc - tic):.4f} ms")
# iterative approach
tic = time.time()
c = my_dot(a,b)
toc = time.time()
print(f"{c:.4f} , time taken by vectorized approach,{1000 * (toc - tic):.4f} ms")


2501072.5817 , time taken by vectorized approach,6.0010 ms
2501072.5817 , time taken by vectorized approach,1953.2516 ms


Matrix (2D Arrays)

In [58]:
a = np.zeros((1,2))
print(a)
b = np.zeros((2,1))
print(b)

[[0. 0.]]
[[0.]
 [0.]]


In [63]:
a = np.array([[2],[3],[4]])
print(a , a.shape)
b = np.array([[1,2,3]])
print(b , b.shape)

[[2]
 [3]
 [4]] (3, 1)
[[1 2 3]] (1, 3)


Matrix Indexing

In [68]:
a = np.arange(6).reshape(-1,2)
print(a)
# accessing an element
print(a[2,0])
# accessing the row
print(a[2])

[[0 1]
 [2 3]
 [4 5]]
4
[4 5]


Slicing The Matrix

a[row number,column number]

a[m,n]

In [77]:
a = np.arange(20).reshape(-1,10)
print(a)
# access 5 elements of 1st row
print(a[0,2:7:1])
# access 5 elements from 2 rows
print(a[:,2:7:1])
# access all elements
print(a[:,:])
# access elements from 1st row
print(a[0,])
# OR
print(a[0])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[2 3 4 5 6]
[[ 2  3  4  5  6]
 [12 13 14 15 16]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Nice! Now you have good understanding about basic numpy features for ML